import RiemannianFluids.Analysis.ClosedOperators
import Mathlib.Analysis.InnerProductSpace.Symmetric

/-!
# Operators generated by a bounded resolvent

Let `R : H →L[𝕜] H` be injective.  This module constructs the partially defined operator

    A (R f) = f - R f

with domain `range R`.  The graph is characterized by the closed equation

    R (u + v) = u,

so `A` is closed.  If `R` is symmetric, then injectivity forces `range R` to be dense and the
adjoint equation shows that `A` is self-adjoint.  This is the functional-analytic mechanism used
by form resolvents such as the Hodge--Stokes resolvent; it is independent of the underlying
geometry and of how `R` was constructed.
-/

noncomputable section

namespace RiemannianFluids

open Set
open scoped LinearPMap

variable {𝕜 H : Type*} [RCLike 𝕜]
  [NormedAddCommGroup H] [InnerProductSpace 𝕜 H]

/-- Core-coordinate action for the operator generated by `R`: `f ↦ f - R f`. -/
noncomputable def resolventGeneratedCoreOperator (R : H →L[𝕜] H) : H →ₗ[𝕜] H :=
  LinearMap.id - R.toLinearMap

/-- The partial operator `R⁻¹ - I`, defined on the actual range of an injective bounded
resolvent. -/
noncomputable def resolventGeneratedOperator (R : H →L[𝕜] H)
    (hR : Function.Injective R) : H →ₗ.[𝕜] H :=
  linearPMapOfInjectiveCore R.toLinearMap hR (resolventGeneratedCoreOperator R)

@[simp] theorem resolventGeneratedOperator_domain (R : H →L[𝕜] H)
    (hR : Function.Injective R) :
    (resolventGeneratedOperator R hR).domain = R.toLinearMap.range :=
  rfl

/-- Canonical domain element represented by the resolvent input `f`. -/
noncomputable def resolventGeneratedDomainElement (R : H →L[𝕜] H)
    (hR : Function.Injective R) (f : H) :
    (resolventGeneratedOperator R hR).domain :=
  ⟨R f, ⟨f, rfl⟩⟩

@[simp] theorem resolventGeneratedDomainElement_coe (R : H →L[𝕜] H)
    (hR : Function.Injective R) (f : H) :
    (resolventGeneratedDomainElement R hR f : H) = R f :=
  rfl

/-- The defining equation `A (R f) = f - R f`. -/
@[simp] theorem resolventGeneratedOperator_apply_resolvent (R : H →L[𝕜] H)
    (hR : Function.Injective R) (f : H) :
    resolventGeneratedOperator R hR (resolventGeneratedDomainElement R hR f) =
      f - R f := by
  let x : (resolventGeneratedOperator R hR).domain :=
    ⟨R.toLinearMap f, ⟨f, rfl⟩⟩
  have hx : resolventGeneratedDomainElement R hR f = x := by
    apply Subtype.ext
    rfl
  rw [hx]
  calc
    resolventGeneratedOperator R hR x = resolventGeneratedCoreOperator R f := by
      simpa only [x, resolventGeneratedOperator] using
        linearPMapOfInjectiveCore_apply R.toLinearMap hR
          (resolventGeneratedCoreOperator R) f
    _ = f - R f := rfl

/-- Every domain element has a resolvent representation.  Injectivity makes its coordinate
unique, although existence is the form most downstream graph arguments need. -/
theorem resolventGeneratedOperator_exists_resolvent_representation
    (R : H →L[𝕜] H) (hR : Function.Injective R)
    (x : (resolventGeneratedOperator R hR).domain) :
    ∃ f : H, x = resolventGeneratedDomainElement R hR f := by
  rcases x.property with ⟨f, hf⟩
  refine ⟨f, ?_⟩
  apply Subtype.ext
  exact hf.symm

/-- The graph of `R⁻¹ - I` is the zero set of the continuous resolvent equation. -/
theorem resolventGeneratedOperator_pair_mem_graph_iff
    (R : H →L[𝕜] H) (hR : Function.Injective R) (u v : H) :
    (u, v) ∈ (resolventGeneratedOperator R hR).graph ↔ R (u + v) = u := by
  constructor
  · intro huv
    rcases (resolventGeneratedOperator R hR).mem_graph_iff.mp huv with
      ⟨x, hx, hAx⟩
    rcases resolventGeneratedOperator_exists_resolvent_representation R hR x with
      ⟨f, rfl⟩
    rw [resolventGeneratedOperator_apply_resolvent] at hAx
    have hx' : R f = u := by
      simpa only [resolventGeneratedDomainElement_coe] using hx
    change f - R f = v at hAx
    have hsum : u + v = f := by
      rw [← hx', ← hAx]
      abel
    rw [hsum]
    exact hx'
  · intro huv
    apply (resolventGeneratedOperator R hR).mem_graph_iff.mpr
    refine ⟨resolventGeneratedDomainElement R hR (u + v), ?_, ?_⟩
    · exact huv
    · rw [resolventGeneratedOperator_apply_resolvent, huv]
      abel

/-- A bounded injective resolvent always generates a closed operator. -/
theorem resolventGeneratedOperator_isClosed (R : H →L[𝕜] H)
    (hR : Function.Injective R) :
    (resolventGeneratedOperator R hR).IsClosed := by
  rw [LinearPMap.IsClosed]
  have hgraph :
      ((resolventGeneratedOperator R hR).graph : Set (H × H)) =
        {p | R (p.1 + p.2) = p.1} := by
    ext p
    exact resolventGeneratedOperator_pair_mem_graph_iff R hR p.1 p.2
  rw [hgraph]
  exact isClosed_eq
    (R.continuous.comp (continuous_fst.add continuous_snd)) continuous_fst

/-- A symmetric injective bounded operator has dense range. -/
theorem symmetric_injective_denseRange [CompleteSpace H] (R : H →L[𝕜] H)
    (hSymmetric : R.toLinearMap.IsSymmetric) (hR : Function.Injective R) :
    DenseRange R := by
  change Dense (R.toLinearMap.range : Set H)
  rw [Submodule.dense_iff_topologicalClosure_eq_top]
  rw [← Submodule.orthogonal_orthogonal_eq_closure]
  rw [hSymmetric.orthogonal_range]
  rw [(LinearMap.ker_eq_bot).2 hR]
  exact Submodule.bot_orthogonal_eq_top

/-- The generated operator has dense domain whenever the resolvent has dense range. -/
theorem resolventGeneratedOperator_dense_domain (R : H →L[𝕜] H)
    (hR : Function.Injective R) (hDense : DenseRange R) :
    Dense ((resolventGeneratedOperator R hR).domain : Set H) :=
  linearPMapOfInjectiveCore_dense_domain R.toLinearMap hR
    (resolventGeneratedCoreOperator R) hDense

/-- Symmetry of the bounded resolvent gives symmetry of the generated partial operator. -/
theorem resolventGeneratedOperator_isFormalAdjoint (R : H →L[𝕜] H)
    (hR : Function.Injective R) (hSymmetric : R.toLinearMap.IsSymmetric) :
    (resolventGeneratedOperator R hR).IsFormalAdjoint
      (resolventGeneratedOperator R hR) := by
  intro x y
  rcases resolventGeneratedOperator_exists_resolvent_representation R hR x with
    ⟨f, rfl⟩
  rcases resolventGeneratedOperator_exists_resolvent_representation R hR y with
    ⟨g, rfl⟩
  rw [resolventGeneratedOperator_apply_resolvent,
    resolventGeneratedOperator_apply_resolvent]
  change inner 𝕜 (f - R f) (R g) = inner 𝕜 (R f) (g - R g)
  rw [inner_sub_left, inner_sub_right]
  exact congrArg (fun z : 𝕜 => z - inner 𝕜 (R f) (R g))
    (hSymmetric f g).symm

/-- The adjoint-domain equation.  If `y` lies in the adjoint domain and `z = A† y`, symmetry of
`R` forces `R (y + z) = y`; hence every adjoint-domain vector already lies in `range R`. -/
theorem resolventGeneratedOperator_adjoint_resolvent
    [CompleteSpace H] (R : H →L[𝕜] H) (hR : Function.Injective R)
    (hSymmetric : R.toLinearMap.IsSymmetric)
    (y : (resolventGeneratedOperator R hR).adjoint.domain) :
    R ((y : H) + (resolventGeneratedOperator R hR).adjoint y) = y := by
  let A := resolventGeneratedOperator R hR
  have hDenseR : DenseRange R := symmetric_injective_denseRange R hSymmetric hR
  have hDenseA : Dense (A.domain : Set H) :=
    resolventGeneratedOperator_dense_domain R hR hDenseR
  have hAdj : A.adjoint.IsFormalAdjoint A := A.adjoint_isFormalAdjoint hDenseA
  apply ext_inner_right 𝕜
  intro f
  have hAdjTest :
      inner 𝕜 (A.adjoint y) (R f) =
        inner 𝕜 (y : H) (f - R f) := by
    simpa only [A, resolventGeneratedDomainElement_coe,
      resolventGeneratedOperator_apply_resolvent] using
      hAdj y (resolventGeneratedDomainElement R hR f)
  calc
    inner 𝕜 (R ((y : H) + A.adjoint y)) f =
        inner 𝕜 ((y : H) + A.adjoint y) (R f) :=
      hSymmetric _ _
    _ = inner 𝕜 (y : H) (R f) + inner 𝕜 (A.adjoint y) (R f) :=
      inner_add_left _ _ _
    _ = inner 𝕜 (y : H) (R f) + inner 𝕜 (y : H) (f - R f) := by
      rw [hAdjTest]
    _ = inner 𝕜 (y : H) f := by
      rw [inner_sub_right]
      abel

/-- A symmetric injective bounded resolvent generates a self-adjoint unbounded operator. -/
theorem resolventGeneratedOperator_isSelfAdjoint (R : H →L[𝕜] H)
    [CompleteSpace H] (hR : Function.Injective R)
    (hSymmetric : R.toLinearMap.IsSymmetric) :
    IsSelfAdjoint (resolventGeneratedOperator R hR) := by
  rw [LinearPMap.isSelfAdjoint_def]
  let A := resolventGeneratedOperator R hR
  have hDenseR : DenseRange R := symmetric_injective_denseRange R hSymmetric hR
  have hDenseA : Dense (A.domain : Set H) :=
    resolventGeneratedOperator_dense_domain R hR hDenseR
  apply le_antisymm
  · refine ⟨?_, ?_⟩
    · intro y hy
      let yAdj : A.adjoint.domain := ⟨y, hy⟩
      let z : H := A.adjoint yAdj
      have hRyz : R (y + z) = y := by
        simpa only [A, yAdj, z] using
          resolventGeneratedOperator_adjoint_resolvent R hR hSymmetric yAdj
      change y ∈ R.toLinearMap.range
      exact ⟨y + z, hRyz⟩
    · intro yAdj yA hcoe
      let z : H := A.adjoint yAdj
      have hRyz : R ((yAdj : H) + z) = yAdj := by
        simpa only [A, z] using
          resolventGeneratedOperator_adjoint_resolvent R hR hSymmetric yAdj
      have hyA : yA = resolventGeneratedDomainElement R hR ((yAdj : H) + z) := by
        apply Subtype.ext
        calc
          (yA : H) = (yAdj : H) := hcoe.symm
          _ = R ((yAdj : H) + z) := hRyz.symm
          _ = (resolventGeneratedDomainElement R hR ((yAdj : H) + z) : H) := rfl
      rw [hyA, resolventGeneratedOperator_apply_resolvent]
      change A.adjoint yAdj = (yAdj : H) + A.adjoint yAdj -
        R ((yAdj : H) + A.adjoint yAdj)
      rw [resolventGeneratedOperator_adjoint_resolvent R hR hSymmetric yAdj]
      abel
  · exact (resolventGeneratedOperator_isFormalAdjoint R hR hSymmetric).le_adjoint hDenseA

end RiemannianFluids
