import Mathlib.Data.Real.Basic

/-!
# Differential-form calculus contracts

The analytic papers use differential forms in fixed adjacent degrees, not only smooth vector
fields.  This module records the primitive operations needed by CC13, CC15, CCD17, and CCP25
without pretending that mathlib's current differential-form API already supplies their global
noncompact Sobolev theory.

`FormDegreeCalculus` is deliberately data-only.  Nilpotence, adjointness, Weitzenbock
identities, weak extensions, and closed-range results are propositions in later modules.  In
particular, none of the mathematical conclusions to be proved are stored as structure fields.
-/

namespace RiemannianFluids

/-- Operations involving one fixed form degree and its two adjacent degrees. -/
structure FormDegreeCalculus
    (Lower Form Upper CovariantDerivative : Type*) where
  /-- Exterior derivative from degree `k - 1` to degree `k`. -/
  exteriorFromLower : Lower → Form
  /-- Exterior derivative from degree `k` to degree `k + 1`. -/
  exterior : Form → Upper
  /-- Codifferential from degree `k + 1` to degree `k`. -/
  codifferentialFromUpper : Upper → Form
  /-- Codifferential from degree `k` to degree `k - 1`. -/
  codifferential : Form → Lower
  /-- Levi--Civita covariant derivative of a degree-`k` form. -/
  covariantDerivative : Form → CovariantDerivative
  /-- Analysis-positive Hodge Laplacian `d d* + d* d`. -/
  hodgeLaplacian : Form → Form
  /-- Analysis-positive Bochner Laplacian `nabla* nabla`. -/
  bochnerLaplacian : Form → Form
  /-- Smoothness at the regularity used by a source theorem. -/
  isSmooth : Form → Prop
  /-- Compact support. -/
  hasCompactSupport : Form → Prop
  /-- Square integrability. -/
  isL2 : Form → Prop
  /-- First-order Sobolev membership. -/
  isH1 : Form → Prop
  /-- The `L2` pairing at this degree. -/
  l2Pairing : Form → Form → ℝ
  /-- The covariant-derivative pairing used in the `H1` inner product. -/
  derivativePairing : CovariantDerivative → CovariantDerivative → ℝ

/-- A form is closed when its exterior derivative vanishes. -/
def IsClosedForm
    {Lower Form Upper CovariantDerivative : Type*}
    [Zero Upper]
    (calculus : FormDegreeCalculus Lower Form Upper CovariantDerivative)
    (form : Form) : Prop :=
  calculus.exterior form = 0

/-- A form is co-closed when its codifferential vanishes. -/
def IsCoClosedForm
    {Lower Form Upper CovariantDerivative : Type*}
    [Zero Lower]
    (calculus : FormDegreeCalculus Lower Form Upper CovariantDerivative)
    (form : Form) : Prop :=
  calculus.codifferential form = 0

/-- A source-level harmonic form lies in `L2` and is killed by the Hodge Laplacian. -/
def IsL2HarmonicForm
    {Lower Form Upper CovariantDerivative : Type*}
    [Zero Form]
    (calculus : FormDegreeCalculus Lower Form Upper CovariantDerivative)
    (form : Form) : Prop :=
  calculus.isL2 form ∧ calculus.hodgeLaplacian form = 0

/-- The `H1` pairing `(u,v) + (nabla u,nabla v)` used in CCP25 equation (4.3). -/
def FormDegreeCalculus.h1Pairing
    {Lower Form Upper CovariantDerivative : Type*}
    (calculus : FormDegreeCalculus Lower Form Upper CovariantDerivative)
    (first second : Form) : ℝ :=
  calculus.l2Pairing first second +
    calculus.derivativePairing
      (calculus.covariantDerivative first)
      (calculus.covariantDerivative second)

/-- The exact part generated by compactly supported `(k-1)`-forms. -/
def IsCompactlyGeneratedExact
    {Lower Form Upper CovariantDerivative : Type*}
    (calculus : FormDegreeCalculus Lower Form Upper CovariantDerivative)
    (form : Form) : Prop :=
  ∃ lower, calculus.hasCompactSupport (calculus.exteriorFromLower lower) ∧
    calculus.exteriorFromLower lower = form

/-- The coexact part generated by compactly supported `(k+1)`-forms. -/
def IsCompactlyGeneratedCoexact
    {Lower Form Upper CovariantDerivative : Type*}
    (calculus : FormDegreeCalculus Lower Form Upper CovariantDerivative)
    (form : Form) : Prop :=
  ∃ upper, calculus.hasCompactSupport (calculus.codifferentialFromUpper upper) ∧
    calculus.codifferentialFromUpper upper = form

end RiemannianFluids
