import RiemannianFluids

/-!
# Axiom audit for the expository kernel

Formal exposition is useful only if the reader can tell which parts Lean has checked and which parts the theorem merely assumes. A successful
elaboration is not enough: Lean can elaborate a declaration containing an unfinished proof placeholder, whose proof then depends on an unsafe
primitive.

Each command below asks Lean for the logical axioms used by one representative milestone in the argument, in dependency order:

    covariant derivative
      → connection-derived curvature commutator
      → pointwise continuous curvature tensor in all three tangent slots
      → basis-independent Ricci contraction and downstream adapters
      → musical inverse laws
      → scalar gradient and divergence
      → tensor lowering, transpose, and symmetrization
      → intrinsic strain, metric Lie derivative, and codifferential
      → divergence-free curvature comparison
      → second covariant derivative, Ricci commutation, and divergence commutation
      → constructed rough/deformation Laplacian comparison
      → constructed exterior derivative, constructed Hodge Laplacian, and Weitzenböck
      → fully constructed CCD17 divergence-free comparison
      → constructed candidate inequivalence and its concrete hyperbolic witness
      → bundled candidate inequivalence and boundary-selection algebra
      → abstract pressure, energy cancellations, and Grönwall energy decay.

`make lean/check` executes this file and rejects every dependency outside the explicit allowlist
`propext`, `Classical.choice`, and `Quot.sound`.

This audit does **not** turn explicit hypotheses into proved geometry. For example, `ccd17_divfree_def_hodge` receives the Weitzenböck and
symmetric-gradient identities as arguments, whereas `ccd17_divfree_def_rough_constructed` proves the deformation/rough/Ricci comparison outright
from the packaged Levi-Civita connection, and `ccd17_divfree_def_hodge_constructed` proves the full Hodge-form comparison with every operator —
including both de Rham halves of the Hodge Laplacian and the Weitzenböck identity `weitzenbock_constructedAt` — constructed from that connection.
The audit establishes the more precise claim that each conclusion follows from its visible hypotheses with no hidden project postulate or
unfinished proof. That distinction is exactly the formal boundary described in `docs/formal-analysis.md`.
-/

#print axioms RiemannianFluids.LeviCivitaConnection.covariantDerivative_apply
#print axioms RiemannianFluids.LeviCivitaConnection.eq_on_mdifferentiable
#print axioms RiemannianFluids.connectionCurvatureCommutatorData_hasCommutator
#print axioms RiemannianFluids.connectionCurvatureAction_swap
#print axioms RiemannianFluids.connectionCurvatureDirectionsAt_apply
#print axioms RiemannianFluids.connectionCurvatureDirectionsAt_swap
#print axioms RiemannianFluids.hasConnectionCurvatureRegularityAt_of_contMDiff
#print axioms RiemannianFluids.connectionCurvatureAction_tensorial_field_smul
#print axioms RiemannianFluids.connectionCurvatureAction_field_pointwise
#print axioms RiemannianFluids.connectionCurvatureTensorAt_apply
#print axioms RiemannianFluids.connectionCurvatureTensorAt_swap
#print axioms RiemannianFluids.connectionRicciFormAt_eq_sum_inner
#print axioms RiemannianFluids.connectionRicciActionAt_inner
#print axioms RiemannianFluids.ricciActionOfRegularCurvatureTensor_apply
#print axioms RiemannianFluids.connectionScalarCurvatureField_apply
#print axioms RiemannianFluids.connectionRiemannianCurvatureDataOfRegularCurvature_sectionalCurvature
#print axioms RiemannianFluids.hasConnectionRicciRegularity_of_contraction
#print axioms RiemannianFluids.connectionRiemannianCurvatureData_ricciAction
#print axioms RiemannianFluids.RicciData.ofConnection_endomorphism_apply
#print axioms RiemannianFluids.RicciData.ofRegularConnection_endomorphism_apply
#print axioms RiemannianFluids.sharp_flat
#print axioms RiemannianFluids.flat_sharp
#print axioms RiemannianFluids.gradient_characterization
#print axioms RiemannianFluids.isDivergenceFree_iff_pointwise
#print axioms RiemannianFluids.covariantDerivativeTensor_apply
#print axioms RiemannianFluids.transposeCovariantTwoTensor_apply
#print axioms RiemannianFluids.symmetrizeCovariantTwoTensor_apply
#print axioms RiemannianFluids.antisymmetrizeCovariantTwoTensor_apply
#print axioms RiemannianFluids.symmetrize_add_antisymmetrize_eq_self
#print axioms RiemannianFluids.deformationTensor_apply
#print axioms RiemannianFluids.deformationTensor_symmetric
#print axioms RiemannianFluids.infinitesimalMetricRate_apply
#print axioms RiemannianFluids.metricLieDerivativeAt_leviCivita
#print axioms RiemannianFluids.metricLieDerivativeAt_eq_two_deformationTensor
#print axioms RiemannianFluids.infinitesimalMetricRate_eq_metricLieDerivativeAt
#print axioms RiemannianFluids.codifferentialOne_flat
#print axioms RiemannianFluids.exactCodifferentialCorrection_eq_zero_of_divergenceFree
#print axioms RiemannianFluids.ccd17_positive_full
#print axioms RiemannianFluids.ccd17_divfree_def_hodge
#print axioms RiemannianFluids.secondCovariantDerivativeAt_apply
#print axioms RiemannianFluids.secondCovariantDerivativeAlong_sub_swap
#print axioms RiemannianFluids.secondCovariantDerivativeAt_sub_swap
#print axioms RiemannianFluids.deformationCovariantDerivativeAt_eq_secondDerivative
#print axioms RiemannianFluids.sum_deformationCovariantDerivativeAt_extend
#print axioms RiemannianFluids.bilinearMixedTraceAgainst_secondCovariantDerivativeAt
#print axioms RiemannianFluids.divergenceCommutationAt_of_leviCivita
#print axioms RiemannianFluids.deformationLaplacian_rough_ricci_comparisonAt
#print axioms RiemannianFluids.deformationLaplacian_rough_ricci_comparisonAt_of_divergenceFree
#print axioms RiemannianFluids.deformationLaplacian_rough_ricci_comparisonVectorAt_of_divergenceFree
#print axioms RiemannianFluids.ccd17_divfree_def_rough_constructed
#print axioms RiemannianFluids.exteriorDerivativeValueAt_eq_mlieBracket
#print axioms RiemannianFluids.exteriorDerivativeTensor_eq_exteriorDerivativeValueAt
#print axioms RiemannianFluids.exteriorDerivativeTensor_eq_two_antisymmetrize
#print axioms RiemannianFluids.covariantDerivativeTensorCovariantDerivativeAt_eq_secondDerivative
#print axioms RiemannianFluids.exteriorDerivativeCovariantDerivativeAt_eq_secondDerivative
#print axioms RiemannianFluids.sum_exteriorDerivativeCovariantDerivativeAt_extend
#print axioms RiemannianFluids.hodgeExactHalfTestedAt_eq_exactCodifferentialCorrectionOne
#print axioms RiemannianFluids.weitzenbock_constructedAt
#print axioms RiemannianFluids.weitzenbock_constructedVectorAt
#print axioms RiemannianFluids.ccd17_full_constructedAt
#print axioms RiemannianFluids.ccd17_divfree_def_hodge_constructed
#print axioms RiemannianFluids.candidateOperators_pairwiseDistinct_of_curvatureWitness
#print axioms RiemannianFluids.constructedCandidateTests_pairwiseDistinct_of_ricciWitness
#print axioms RiemannianFluids.constructedCandidateOutputs_pairwiseDistinct_of_ricciWitness
#print axioms RiemannianFluids.wbs26_analysisPositive_crosswalk
#print axioms RiemannianFluids.boundarySelectedOperator_zero
#print axioms RiemannianFluids.boundarySelectedOperator_one
#print axioms RiemannianFluids.pressure_work_eq_zero
#print axioms RiemannianFluids.navierStokes_energy_identity
#print axioms RiemannianFluids.energy_exponential_decay
#print axioms RiemannianFluids.energy_exponential_decay_of_coercive_dissipation
#print axioms RiemannianFluids.resolventGeneratedOperator_isSelfAdjoint
#print axioms RiemannianFluids.Literature.CZ24.operator_census_hyperbolic_witness
#print axioms RiemannianFluids.Literature.CCD17.divergenceFree_deformation_eq_hodge_sub_two_ricci
#print axioms RiemannianFluids.Literature.CCG25.gauss_ricci_codimension_two_of_euclidean_gauss
#print axioms RiemannianFluids.Literature.CCG25.bochner_laplacian_gauss_general_codimension_of_gaussWeingarten
#print axioms RiemannianFluids.Literature.CCG25.hodge_laplacian_gauss_general_codimension_of_weizenbock
#print axioms RiemannianFluids.Literature.CCG25.bochner_laplacian_gauss_general_codimension_of_isometric_immersion
#print axioms RiemannianFluids.Literature.CCG25.hodge_laplacian_gauss_general_codimension_of_isometric_immersion
#print axioms RiemannianFluids.Literature.CCG25.bochner_laplacian_gauss_general_codimension_of_smooth_tangent_field
#print axioms RiemannianFluids.Literature.CCG25.hodge_laplacian_gauss_general_codimension_of_smooth_tangent_field
#print axioms RiemannianFluids.Literature.CCG25.bochner_laplacian_gauss_general_codimension_with_constructed_operators
#print axioms RiemannianFluids.Literature.CCG25.hodge_laplacian_gauss_general_codimension_with_constructed_operators
#print axioms RiemannianFluids.CovariantSubmanifoldFieldExtensionData.covariantDerivativeSecondFundamentalAlong_eq_point_of_smooth
#print axioms RiemannianFluids.geodesicFrameFieldAt_covariantDerivative_eq_zero
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianInputDataAt.toSourceData
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianSourceDataAt.meanNormalField_derivative
#print axioms RiemannianFluids.Literature.CCG25.bochner_laplacian_gauss_general_codimension_from_geodesic_frame
#print axioms RiemannianFluids.Literature.CCG25.hodge_laplacian_gauss_general_codimension_from_geodesic_frame
#print axioms RiemannianFluids.Literature.CCG25.bochner_laplacian_gauss_general_codimension_from_smooth_field
#print axioms RiemannianFluids.Literature.CCG25.hodge_laplacian_gauss_general_codimension_from_smooth_field
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianFieldJetDataAt.intrinsicBochner_eq_mfderiv_roughLaplacianAt
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianFieldJetDataAt.normalSecondDerivativeTrace_sub_acceleration_eq
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianFieldJetDataAt.ambientTangentHessianDiagonal_eq_pointGauss
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianFieldJetDataAt.hasAmbientTangentHessianTraceGaussAt
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianFieldJetDataAt.ambientBochner_eq_roughLaplacianAt
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianFieldJetDataAt.intrinsicHodge_eq_mfderiv_hodgeLaplacianConstructedAt
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianFieldJetDataAt.ambientHodge_eq_hodgeLaplacianConstructedAt
#print axioms RiemannianFluids.LeviCivitaConnection.connectionCurvatureFirstBianchiAt
#print axioms RiemannianFluids.LeviCivitaConnection.connectionCurvatureMetricSkewAt
#print axioms RiemannianFluids.LeviCivitaConnection.connectionRicciSymmetricAt
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianFieldJetDataAt.intrinsicHodge_eq_mfderiv_hodgeLaplacianConstructedAt_of_leviCivita
#print axioms RiemannianFluids.SmoothSubmanifoldLaplacianFieldJetDataAt.ambientHodge_eq_hodgeLaplacianConstructedAt_of_leviCivita
#print axioms RiemannianFluids.Literature.CCY23.invariant_restriction_axisymmetric_ellipsoid
#print axioms RiemannianFluids.Literature.CCY23.section4_radial_extension
#print axioms RiemannianFluids.Literature.CCY23.eccentricity_expansion_axisymmetric_ellipsoid
#print axioms RiemannianFluids.Literature.CCF25.EllipsoidCandidateConstruction.four_candidates_sphere
#print axioms RiemannianFluids.SmoothIsometricImmersionData.isOrthogonalSubmanifoldSplitting
#print axioms RiemannianFluids.SmoothIsometricImmersionData.mem_normalSpace_iff
#print axioms RiemannianFluids.SubmanifoldFieldExtensionData.ambientDerivativeTangent_eq_gauss
#print axioms RiemannianFluids.SubmanifoldFieldExtensionData.ambientDerivativeAlong_eq_weingarten
#print axioms RiemannianFluids.SubmanifoldFieldExtensionData.projectedSecondFundamentalFormAt_apply
#print axioms RiemannianFluids.SubmanifoldFieldExtensionData.projectedSecondFundamentalFormAt_comm
#print axioms RiemannianFluids.isometricConnectionSubmanifoldPointwiseGaussDataAt_isSymmetric
#print axioms RiemannianFluids.SubmanifoldFieldExtensionData.linearFiberExtensionAt_mdifferentiableAt
#print axioms RiemannianFluids.SubmanifoldFieldExtensionData.linearFiberExtensionAt_contMDiffAt_two
#print axioms RiemannianFluids.VectorField.lieBracket_eq_fderiv_lieBracket_of_related
#print axioms RiemannianFluids.VectorField.mlieBracket_eq_mfderiv_mlieBracket_of_related
#print axioms RiemannianFluids.LeviCivitaConnection.eq_on_mfderiv_of_comp_eq
#print axioms RiemannianFluids.CovariantSubmanifoldFieldExtensionData.inducedCovariantDerivative_apply
#print axioms RiemannianFluids.CovariantSubmanifoldFieldExtensionData.hasBracketCompatibility
#print axioms RiemannianFluids.CovariantSubmanifoldFieldExtensionData.ambientDerivativeTangent_eq_gauss_inducedCovariantDerivative
#print axioms RiemannianFluids.CovariantSubmanifoldFieldExtensionData.inducedCovariantDerivative_torsionFree
#print axioms RiemannianFluids.CovariantSubmanifoldFieldExtensionData.inducedCovariantDerivative_metricCompatible
#print axioms RiemannianFluids.CovariantSubmanifoldFieldExtensionData.projectedSecondFundamentalFormAt_comm
#print axioms RiemannianFluids.CovariantSubmanifoldFieldExtensionData.inducedCovariantDerivative_independent
#print axioms RiemannianFluids.PointwiseGaussData.hasGaussEquationRelativeTo_of_vector
#print axioms RiemannianFluids.PointwiseGaussData.hasEuclideanGaussEquation_of_relative_eq_zero
#print axioms RiemannianFluids.tangentialAmbientConnectionCurvatureAt_apply
#print axioms RiemannianFluids.SmoothIsometricImmersionData.adaptedAmbientOrthonormalBasisAt
#print axioms RiemannianFluids.normalFrameAmbientRicciActionAt_inner
#print axioms RiemannianFluids.SmoothIsometricImmersionData.connectionRicciActionAlong_eq_adaptedTraceAt
#print axioms RiemannianFluids.isometricConnectionSubmanifoldRicciGaussJetAt_hasAmbientRicciTraceSplitting
#print axioms RiemannianFluids.shapeOperatorAlong_inner_secondFundamentalFormAlong
#print axioms RiemannianFluids.shapeOperatorOfProjectedSecondFundamentalAt_eq_shapeOperatorAlong
#print axioms RiemannianFluids.inducedCurvatureAction_eq_tangentialAmbient_add_shape
#print axioms RiemannianFluids.inducedLeviCivitaSubmanifoldPointwiseGaussDataAt_hasVectorGaussEquationRelativeTo
#print axioms RiemannianFluids.inducedLeviCivitaSubmanifoldPointwiseGaussDataAt_hasGaussEquationRelativeTo
#print axioms RiemannianFluids.inducedLeviCivitaSubmanifoldPointwiseGaussDataAt_hasEuclideanGaussEquation
#print axioms RiemannianFluids.inducedLeviCivitaSubmanifoldPointwiseGaussDataAt_isSymmetric
#print axioms RiemannianFluids.Literature.CCG25.gauss_ricci_codimension_two_of_isometric_immersion
#print axioms RiemannianFluids.Literature.WBK26.metric_rate_eq_twice_deformation
#print axioms RiemannianFluids.Literature.WBK26.material_inner_product_rate_eq_twice_deformation
#print axioms RiemannianFluids.Literature.WBK26.exponential_decay_of_energy_identity_and_coercivity
#print axioms RiemannianFluids.Literature.WBS26.local_interpolating_family_analysisPositive
#print axioms RiemannianFluids.Literature.CCP25.h2_oneForm_h1_decomposition
#print axioms RiemannianFluids.DistributionalLeibniz.tempered_lineDeriv_smulLeft_of_compactSupport
#print axioms RiemannianFluids.DistributionalLeibniz.tempered_laplacian_smulLeft_of_compactSupport
#print axioms RiemannianFluids.EuclideanEllipticRegularity.besselPotential_two_eq_sub_laplacian
#print axioms RiemannianFluids.EuclideanEllipticRegularity.memSobolev_add_two_of_laplacian
#print axioms RiemannianFluids.EuclideanEllipticRegularity.memSobolev_one_of_laplacian_memSobolev_neg_one
#print axioms RiemannianFluids.EuclideanEllipticRegularity.localized_memSobolev_one_of_laplacian
#print axioms RiemannianFluids.EuclideanSobolev.exists_sobolevOneCoordinate
#print axioms RiemannianFluids.EuclideanSobolev.sobolevOneLineDeriv_toTemperedDistribution
#print axioms RiemannianFluids.EuclideanSobolev.localized_weak_energy_identity
#print axioms RiemannianFluids.HyperbolicPlane.poincareMetric
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicLeviCivitaConnection
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolic_metricCompatible
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicCovariantDerivative_torsion
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicCovariantDerivative_contMDiff
#print axioms RiemannianFluids.HyperbolicPlane.horizontalField_isDivergenceFree
#print axioms RiemannianFluids.HyperbolicPlane.curvatureAction_coordinate
#print axioms RiemannianFluids.HyperbolicPlane.ricciAction_horizontal_ne_zero
#print axioms RiemannianFluids.HyperbolicPlane.scalarCurvature_neg_two
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolic_hasSurfaceRicciIdentity
#print axioms RiemannianFluids.HyperbolicPlane.cz24_census_hyperbolic
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolic_dist_eq
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicVolume_def
#print axioms RiemannianFluids.HyperbolicPlane.completeRiemannianManifold
#print axioms RiemannianFluids.HyperbolicPlane.norm_oneFormComponentsAt
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicScalarL2_complete
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicOneFormL2_complete
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicSmoothCompactToL2
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicSmoothCompactScalar_dense
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicSmoothCompactOneForm_dense
#print axioms RiemannianFluids.HyperbolicPlane.memLp_ambient_compact_mul_scalar_complex
#print axioms RiemannianFluids.HyperbolicPlane.ambientLocalizedScalarL2_ae
#print axioms RiemannianFluids.HyperbolicPlane.oneFormCodifferential_scalarExterior_eq_neg_height_sq_laplacian
#print axioms RiemannianFluids.HyperbolicPlane.inner_hyperbolicScalarShiftedHodgeCoreL2_eq_euclideanIntegral
#print axioms RiemannianFluids.HyperbolicPlane.localized_laplacian_eq_potential
#print axioms RiemannianFluids.HyperbolicPlane.exists_localized_memSobolev_one
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolic_localized_square_energy_bound
#print axioms RiemannianFluids.HyperbolicPlane.weakScalarShiftedHarmonic_eq_zero
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicScalarShiftedHodgeCoreL2_denseRange
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicSmoothCompactOneFormToH1_denseRange
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicH1_exact_add_coexact_add_harmonic
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHarmonicH1_toL2_mem_harmonic
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHarmonicH1ToHarmonicL2_surjective
#print axioms RiemannianFluids.HyperbolicPlane.norm_sq_hyperbolicHarmonicL2ToH1
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicH1_exact_add_coexact_add_actualHarmonic
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicL2_exact_add_coexact_add_harmonic
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicLerayProjector_eq_self_iff
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesEmbedding_denseRange
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesSolution_variational
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesOperator_isClosed
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesOperator_isSelfAdjoint
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesOperator_weak_identity
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesOperator_isFormalAdjoint
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesOperator_nonnegative
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesOperator_eq_zero_iff_harmonic
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesToDivergenceFreeH1_toL2
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesToDivergenceFreeH1_hodge
#print axioms RiemannianFluids.HyperbolicPlane.hyperbolicHodgeStokesFormDomainEquivDivergenceFreeH1
#print axioms RiemannianFluids.CanonicalTorus.surfaceL2_complete
#print axioms RiemannianFluids.CanonicalTorus.shellL2_complete
#print axioms RiemannianFluids.CanonicalTorus.shellMeasure_le_reference
#print axioms RiemannianFluids.CanonicalTorus.reference_le_two_shellMeasure
#print axioms RiemannianFluids.CanonicalTorus.constantCoordinateLiftL2_ae
#print axioms RiemannianFluids.CanonicalTorus.inner_fluxIdentifyL2_integral
#print axioms RiemannianFluids.CanonicalTorus.norm_constantCoordinateLiftL2_le_eight
#print axioms RiemannianFluids.CanonicalTorus.norm_fluxIdentifyL2_le_eight
#print axioms RiemannianFluids.CanonicalTorus.thicknessAt_tendsto_zero
