"""Intrinsic manifolds, embedded submanifolds, and curvature."""

from riemannian_fluids.geometry.core import (
    Geometry,
    christoffel_symbols,
    covariant_tensor_norm,
    dimension,
    extrinsic_gaussian_curvature,
    gauss_ricci_tensor,
    intrinsic_gaussian_curvature,
    intrinsic_ricci_tensor,
    mean_curvature,
    mean_curvature_vector,
    metric,
    riemann_curvature_tensor,
    scalar_curvature,
    second_fundamental_form,
    second_fundamental_form_vector,
    second_fundamental_forms,
    shape_operator,
    shape_operators,
    tangent_coordinates,
    vector_norm,
    vector_squared_norm,
)
from riemannian_fluids.geometry.domains import CoordinateDomain
from riemannian_fluids.geometry.manifolds import RiemannianManifold, euclidean_space
from riemannian_fluids.geometry.space_forms import (
    hyperbolic_geodesic_polar,
    hyperbolic_poincare_ball,
    hyperbolic_upper_half_space,
    sphere,
    spheroid,
    torus_of_revolution,
)
from riemannian_fluids.geometry.submanifolds import (
    EmbeddedSubmanifold,
    embedding_jacobian,
    euclidean_submanifold,
    normal_frame,
    unit_normal,
)

__all__ = (
    "CoordinateDomain",
    "EmbeddedSubmanifold",
    "Geometry",
    "RiemannianManifold",
    "christoffel_symbols",
    "covariant_tensor_norm",
    "dimension",
    "embedding_jacobian",
    "euclidean_space",
    "euclidean_submanifold",
    "extrinsic_gaussian_curvature",
    "gauss_ricci_tensor",
    "hyperbolic_geodesic_polar",
    "hyperbolic_poincare_ball",
    "hyperbolic_upper_half_space",
    "intrinsic_gaussian_curvature",
    "intrinsic_ricci_tensor",
    "mean_curvature",
    "mean_curvature_vector",
    "metric",
    "normal_frame",
    "riemann_curvature_tensor",
    "scalar_curvature",
    "second_fundamental_form",
    "second_fundamental_form_vector",
    "second_fundamental_forms",
    "shape_operator",
    "shape_operators",
    "sphere",
    "spheroid",
    "tangent_coordinates",
    "torus_of_revolution",
    "unit_normal",
    "vector_norm",
    "vector_squared_norm",
)
