import RiemannianFluids.Tensors.VectorCalculus

/-!
# Intrinsic strain as the kinematic starting point

Viscosity should not enter the theory as an unexplained choice of second-order operator.  Its
first intrinsic datum is the rate at which a velocity field deforms the metric.  For a
Levi-Civita connection this rate is the symmetric part of the metric-lowered covariant
derivative:

    Def u (X,Y) = 1/2 (g (nabla_X u) Y + g (nabla_Y u) X).

This module turns that sentence into the beginning of the thematic development.  The hard
bundle-theoretic work lives in `Tensors.VectorCalculus`: lowering the moving tangent fiber,
showing that tensor transposition is coordinate-natural, and proving that symmetrization
preserves smooth sections.  Here we name the resulting metric-rate tensor and expose the
factor-of-two identity that motivates deformation viscosity.

There is a deliberate boundary.  `infinitesimalMetricRate` is the intrinsic infinitesimal
rate, not yet a Lie derivative constructed from a local flow.  Proving that a flow pullback
has this derivative is a future theorem.  The definition below therefore captures the
kinematic quantity used by the literature without pretending that flow theory is already in
the library.
-/

namespace RiemannianFluids

open Bundle
open scoped ContDiff Manifold

set_option synthInstance.maxHeartbeats 100000

variable
  {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E] [CompleteSpace E]
    [FiniteDimensional ℝ E] [Nontrivial E]
  {H : Type*} [TopologicalSpace H]
  (I : ModelWithCorners ℝ E H)
  {M : Type*} [TopologicalSpace M] [ChartedSpace H M]
    [IsManifold I 2 M]
    [RiemannianBundle (TangentSpace I : M → Type _)]
  [IsContMDiffRiemannianBundle I 1 E (TangentSpace I : M → Type _)]

/-- The intrinsic infinitesimal metric rate generated by a velocity field. -/
noncomputable def infinitesimalMetricRate
    (regularity : ℕ∞ω)
    [IsContMDiffRiemannianBundle I regularity E (TangentSpace I : M → Type _)]
    (connection : LeviCivitaConnection (M := M) I)
    (smooth : LeviCivitaConnection.IsContMDiff I connection regularity) :
    SmoothVectorField (M := M) I (regularity + 1) →ₗ[ℝ]
      SmoothCovariantTwoTensor (M := M) I regularity :=
  (2 : ℝ) • deformationTensor I regularity connection smooth

omit [IsContMDiffRiemannianBundle I 1 E (TangentSpace I : M → Type _)] in
/-- Pointwise, the metric rate is the unsymmetrized derivative plus its transpose. -/
@[simp]
theorem infinitesimalMetricRate_apply
    (regularity : ℕ∞ω)
    [IsContMDiffRiemannianBundle I regularity E (TangentSpace I : M → Type _)]
    (connection : LeviCivitaConnection (M := M) I)
    (smooth : LeviCivitaConnection.IsContMDiff I connection regularity)
    (field : SmoothVectorField (M := M) I (regularity + 1))
    (x : M) (first second : TangentSpace I x) :
    infinitesimalMetricRate I regularity connection smooth field x first second =
      inner ℝ (connection.connection field x first) second +
        inner ℝ (connection.connection field x second) first := by
  simp [infinitesimalMetricRate, deformationTensor_apply]

end RiemannianFluids
