FROM ghcr.io/prefix-dev/pixi:0.74.0@sha256:fcdb4751905901cb984261cdcaf4df4de1562381be2ab54302bb4612d10a4882

WORKDIR /workspace

COPY pixi.toml pixi.lock ./
RUN pixi install --locked

COPY python/riemannian_fluids ./python/riemannian_fluids
COPY python/experiments ./python/experiments

ENTRYPOINT ["pixi", "run", "--locked", "finite-elements"]
