FROM dolfinx/dolfinx:v0.11.0@sha256:2ae4bfbc0d9077268880faf04c72750528bee986c94ab223a2c159969bd56fa8

WORKDIR /workspace

COPY pyproject.toml README.md ./
COPY geometric_viscosity.py ./
COPY riemannian_fluids ./riemannian_fluids
COPY experiments ./experiments
COPY reproductions ./reproductions

RUN python3 -m pip install --no-cache-dir .

ENTRYPOINT ["python3", "-m", "experiments", "finite-elements"]
