import RiemannianFluids.Operators.GeometricIdentities
import RiemannianFluids.Operators.NavierStokes

/-!
# RiemannianFluids

This root contains no mathematical shortcut and no manually maintained proof ladder. It imports the two terminal branches of the current formal
analysis:

* `Operators.GeometricIdentities` ends in the CCD17 deformation/Hodge comparison;
* `Operators.NavierStokes` ends in the abstract instantaneous energy identity.

Every intermediate dependency is encoded by ordinary Lean imports. A Lean IDE can therefore display the actual proof graph: following an edge opens
the module whose expository narrative explains that stage of the argument. The root stays minimal so the graph is generated by the checked
implementation rather than duplicated in a second bookkeeping artifact that could drift.
-/
