"""Symbolic backend: exact chart-level calculus, energy integrals, and thin-shell limits."""

from riemannian_fluids.symbolic.certificates import (
    Certificate,
    DerivationLedger,
    DerivationStep,
    DivergentCertificate,
    ExactCertificate,
    FiniteCertificate,
    UnresolvedCertificate,
)
from riemannian_fluids.symbolic.charts import (
    ChartConstructionError,
    SymbolicManifold,
    hyperbolic_polar_chart,
    positive_symbols,
    sphere_chart,
    spheroid_chart,
    torus_chart,
)
from riemannian_fluids.symbolic.conventions import CONVENTION
from riemannian_fluids.symbolic.crosscheck import CrossCheck, CrossCheckError, crosscheck_components, crosscheck_scalar, require_agreement
from riemannian_fluids.symbolic.fields import (
    CoexactField,
    GradientField,
    RotationKillingField,
    SolenoidalField,
    StructuredField,
    SymbolicScalarField,
    SymbolicVectorField,
    coexact_field,
    gradient_field,
    rotation_killing_field,
)
from riemannian_fluids.symbolic.kernel import (
    christoffel_symbols,
    covariant_derivative_vector,
    covariant_tensor_squared_norm,
    deformation_laplacian,
    deformation_tensor,
    divergence,
    gradient,
    hodge_laplacian,
    lower_index,
    raise_index,
    ricci_action,
    ricci_tensor,
    rough_laplacian,
    scalar_curvature,
    vector_squared_norm,
)
from riemannian_fluids.symbolic.series import EpsSeries, TruncationError, exact_polynomial, series_of
from riemannian_fluids.symbolic.simplify import ExpressionSizeError, exp_normal_zero, expression_size, is_zero, simp

__all__ = [
    "Certificate",
    "CoexactField",
    "DerivationLedger",
    "DerivationStep",
    "DivergentCertificate",
    "EpsSeries",
    "ExactCertificate",
    "FiniteCertificate",
    "GradientField",
    "RotationKillingField",
    "SolenoidalField",
    "StructuredField",
    "SymbolicScalarField",
    "SymbolicVectorField",
    "TruncationError",
    "UnresolvedCertificate",
    "coexact_field",
    "exact_polynomial",
    "exp_normal_zero",
    "gradient_field",
    "rotation_killing_field",
    "series_of",
    "CONVENTION",
    "ChartConstructionError",
    "CrossCheck",
    "CrossCheckError",
    "ExpressionSizeError",
    "SymbolicManifold",
    "christoffel_symbols",
    "covariant_derivative_vector",
    "covariant_tensor_squared_norm",
    "crosscheck_components",
    "crosscheck_scalar",
    "deformation_laplacian",
    "deformation_tensor",
    "divergence",
    "expression_size",
    "gradient",
    "hodge_laplacian",
    "hyperbolic_polar_chart",
    "is_zero",
    "lower_index",
    "positive_symbols",
    "raise_index",
    "require_agreement",
    "ricci_action",
    "ricci_tensor",
    "rough_laplacian",
    "scalar_curvature",
    "simp",
    "sphere_chart",
    "spheroid_chart",
    "torus_chart",
    "vector_squared_norm",
]
